---
apiVersion: kube-create-secret/v1
kind: SecretTemplate
metadata:
  name: my-pkcs12-secret-template
spec:
  metadata:
    name: my-tls-secret-1
    namespace: default
  tls: 
    pkcs12: ref+file://my-keystore.pfx
  type: kubernetes.io/tls
---
apiVersion: kube-create-secret/v1
kind: SecretTemplate
metadata:
  name: my-pkcs12-pems-secret-template
spec:
  metadata:
    name: my-tls-secret-2
    namespace: default
  data:
    tls.key: ref+file://my-key.key
    tls.crt: ref+file://my-certificate.crt
  type: kubernetes.io/tls
---
apiVersion: kube-create-secret/v1
kind: SecretTemplate
metadata:
  name: my-pkcs12-with-password-secret-template
spec:
  metadata:
    name: my-tls-secret-3
    namespace: default
  tls:
    pkcs12: ref+file://my-keystore-with-password.pfx
    password: ref+envsubst://$VAR1
  type: kubernetes.io/tls
---
apiVersion: kube-create-secret/v1
kind: SecretTemplate
metadata:
  name: my-azure-key-vault-cert-secret-template
spec:
  metadata:
    name: my-tls-secret-4
    namespace: default
  tls: 
    pkcs12: ref+azurekeyvault://my-vault/my-vault-certificate
  type: kubernetes.io/tls
---
apiVersion: kube-create-secret/v1
kind: SecretTemplate
metadata:
  name: my-pkcs12-secret-template-with-name
spec:
  metadata:
    name: my-tls-secret-5
    namespace: default
  tls: 
    pkcs12: ref+file://my-keystore.pfx
    name: foo
  type: kubernetes.io/tls
---
apiVersion: kube-create-secret/v1
kind: SecretTemplate
metadata:
  name: my-pkcs12-secret-template-with-names
spec:
  metadata:
    name: my-tls-secret-5
    namespace: default
  tls: 
    pkcs12: ref+file://my-keystore.pfx
    key:
      name: foo.key
    crt:
      name: bar.crt
  type: kubernetes.io/tls
---
apiVersion: kube-create-secret/v1
kind: SecretTemplate
metadata:
  name: my-pkcs12-secret-template-with-certificate-chain-delimiter
spec:
  metadata:
    name: my-tls-secret-5
    namespace: default
  tls: 
    pkcs12: ref+file://my-keystore.pfx
    crt:
      delimiter: ","
  type: kubernetes.io/tls  